name: Deploy Manual

on:
  workflow_dispatch:
    inputs:
      servidor:
        description: 'Servidor'
        required: true
        type: choice
        options:
          - des
          - devqa
      entorno:
        description: 'Entorno'
        required: true
        type: choice
        options:
          - PRD
          - DES

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Definir variables de entorno
        id: vars
        run: |
          if [ "${{ inputs.servidor }}" = "des" ]; then
            echo "PROJECT=DeployDes" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.servidor }}" = "devqa" ]; then
            echo "PROJECT=DeployDevQA" >> $GITHUB_OUTPUT
          fi
          echo "ENTORNO=${{ inputs.entorno }}" >> $GITHUB_OUTPUT
          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Obtener Crumb de Jenkins
        id: crumb
        run: |
          USER="${{ secrets.JENKINS_USER }}"
          PASS="${{ secrets.JENKINS_PASS }}"
          AUTH=$(echo -n "$USER:$PASS" | base64)
          CRUMB=$(curl -s -H "Authorization: Basic $AUTH" ${{ vars.JENKINS_URL }}/crumbIssuer/api/json | jq -r .crumb)
          echo "CRUMB=$CRUMB" >> $GITHUB_OUTPUT

      - name: Ejecutar job de Jenkins
        run: |
          curl -X POST "${{ vars.JENKINS_URL }}/job/${{ steps.vars.outputs.PROJECT }}/buildWithParameters" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_PASS }}" \
            -H "Jenkins-Crumb: ${{ steps.crumb.outputs.CRUMB }}" \
            --data-urlencode "branch=${{ steps.vars.outputs.BRANCH }}" \
            --data-urlencode "entorno=${{ steps.vars.outputs.ENTORNO }}" \
            --data-urlencode "servidor=${{ inputs.servidor }}"
